### ISSUE TITLE
Example of how to use iteratePackagesByClassifier

### ISSUE THREAD

**Issue by bryanhanson** [jkpubsrc/python-module-jk-pypiorgapi#2]
Hello.  I'm interested in searching PiPy.org for packages by keywords.  I'm rather inexperienced with Python.  I tried:

```
api = jk_pypiorgapi.PyPiOrgAPI()
jData = api.iteratePackagesByClassifier(searchTerm="nmr", classifiers=False)
```

and piped the result to a file, but the file is empty.  Can you give an example of how to call this function?  Or am I on the wrong track?

Background: I maintain [FOSS4Spectroscopy](https://bryanhanson.github.io/FOSS4Spectroscopy/) and have automated ways to search Github, CRAN etc, and would like to develop an automated way to search PiPy.org.  Found your answer on [SO](https://stackoverflow.com/a/66671301/633251).

**Comment by jkpubsrc** [comment]
Sorry to answer that late but I didn't notice your question for a few weeks. My apologies. You're the very first to open an issue within two yeas, therefore I didn't expect that at all ;-)

And I just noticed that some methods lacked documentation. So I did three things right now so that you can use the API more easily:
* I improved the `iteratePackagesByClassifier()` and some other methods as some type hints were wrong. This might have led to your confusion.
* I improved the documentation in the `README.md` file to show how the method `iteratePackagesByClassifier()` is used.
* I provided an example in the `examples` directory.

For immediate use here is some example code:

```python
import jk_pypiorgapi

api = jk_pypiorgapi.PyPiOrgAPI()
for jData in api.iteratePackagesByClassifier(
		searchTerm="jk_pypiorgapi",
		classifiers=[
			"Development Status :: 5 - Production/Stable",
			"Development Status :: 6 - Mature",
		]
	):

	print(jData)
```

This example uses `jk_pypiorgapi` as a search term and look for stable and mature packages. As the method `iteratePackagesByClassifier()` provides an iterator/generator you need to use `for` and loop through the results.

If you have any more questions please feel free to ask.

**Comment by jkpubsrc** [comment]
I'll close this issue now. Please feel free to reopen it/open an new one if required!
